[Add:] Improve previous scan credentials regex and add new search environment files function

diff --git a/.github/workflows/scan_credentials.yml b/.github/workflows/scan_credentials.yml
--- a/.github/workflows/scan_credentials.yml
+++ b/.github/workflows/scan_credentials.yml
@@ -25,7 +25,7 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Scan for credentials all files
         id: command_normal_files
-        run: echo "::set-output name=normal_files_value::$(grep -RPHsn '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' * --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')"
+        run: echo "::set-output name=normal_files_value::$(grep -RPHsn '(?<![A-Z0-9])[A]{1}[K]{1}[A-Z0-9]{18}(?![A-Z0-9])' * --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')"
       - name: Validate if credentials exists  
         if: ${{ steps.command_normal_files.outputs.normal_files_value != '0' }}
         run: |
@@ -34,10 +34,20 @@ jobs:
           exit 1
       - name: Scan for credentials hidden files
         id: command_hidden_files
-        run: echo "::set-output name=hidden_files_value::$(grep -RPHsn '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' .[^.]* --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')"
+        run: echo "::set-output name=hidden_files_value::$(grep -RPHsn '(?<![A-Z0-9])[A]{1}[K]{1}[A-Z0-9]{18}(?![A-Z0-9])' .[^.]* --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')"
       - name: Validate if credentials exists in hidden  
         if: ${{ steps.command_hidden_files.outputs.hidden_files_value != '0' }}
         run: |
           echo "::error::AWS credentials was founded, Be careful!"
           echo "::error::${{ steps.command_hidden_files.outputs.hidden_files_value }}"
           exit 1
+      - name: Searching environment files
+        id: command_environment_files
+        run: echo "::set-output name=environment_files_value::$(find -name '*.*env*' || echo '0')"
+      - name: Validate if environment files exists  
+        if: ${{ steps.command_environment_files.outputs.environment_files_value != '0' }}
+        run: |
+          echo "::error::Environment files was founded, watch out!"
+          echo "::error::${{ join(steps.command_environment_files.outputs.*, '\n') }}"
+          exit 1
+      
