Change echo message

diff --git a/.github/workflows/scan_credentials.yml b/.github/workflows/scan_credentials.yml
--- a/.github/workflows/scan_credentials.yml
+++ b/.github/workflows/scan_credentials.yml
@@ -27,11 +27,13 @@ jobs:
       - name: Validate if credentials exists  
         if: ${{ steps.command_normal_files.outputs.normal_files_value != '0' }}
         run: |
-          echo -e '::error::AWS credentials was founded, Be careful!\n${{ steps.command_normal_files.outputs.normal_files_value }}' && exit 1
+          echo "::error::AWS credentials was founded, Be careful!"
+          echo "::error::${{ steps.command_normal_files.outputs.normal_files_value }}" && exit 1
       - name: Scan for credentials hidden files
         id: command_hidden_files
         run: echo "::set-output name=hidden_files_value::$(grep -RPHs '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' .[^.]* || echo -n '0')"
       - name: Validate if credentials exists in hidden  
         if: ${{ steps.command_hidden_files.outputs.hidden_files_value != '0' }}
         run: |
-          echo -e '::error::AWS credentials was founded, Be careful!\n${{ steps.command_hidden_files.outputs.hidden_files_value }}' && exit 1
+          echo "::error::AWS credentials was founded, Be careful!"
+          echo "::error::${{ steps.command_hidden_files.outputs.hidden_files_value }}" && exit 1
