Change error message

diff --git a/.github/workflows/scan_credentials.yml b/.github/workflows/scan_credentials.yml
--- a/.github/workflows/scan_credentials.yml
+++ b/.github/workflows/scan_credentials.yml
@@ -28,8 +28,7 @@ jobs:
         if: ${{ steps.command_normal_files.outputs.normal_files_value != '0' }}
         run: |
           echo "AWS credentials was founded, Be careful!"
-          echo ${{ steps.command_normal_files.outputs.normal_files_value }}
-          exit 1
+          echo "::error::${{ steps.command_normal_files.outputs.normal_files_value }}" && exit 1
       - name: Scan for credentials hidden files
         id: command_hidden_files
         run: echo "::set-output name=hidden_files_value::$(grep -RPHs '(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])' .[^.]* || echo -n '0')"
@@ -37,5 +36,4 @@ jobs:
         if: ${{ steps.command_hidden_files.outputs.hidden_files_value != '0' }}
         run: |
           echo "AWS credentials was founded, Be careful!"
-          echo ${{ steps.command_hidden_files.outputs.hidden_files_value }}
-          exit 1
+          echo "::error::${{ steps.command_hidden_files.outputs.hidden_files_value }}" && exit 1
