Add all steps with multiline

diff --git a/.github/workflows/scan_credentials.yml b/.github/workflows/scan_credentials.yml
--- a/.github/workflows/scan_credentials.yml
+++ b/.github/workflows/scan_credentials.yml
@@ -25,16 +25,22 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Scan for credentials all files
         id: command_normal_files
-        run: echo "normal_files_value=$(grep -RPHsn '(?<![A-Z0-9])[A]{1}[K]{1}[A-Z0-9]{18}(?![A-Z0-9])' * --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')" >> $GITHUB_OUTPUT
+        run: | 
+          echo "normal_files_value<<EOF" >> $GITHUB_OUTPUT
+          echo "$(grep -RPHsn '(?<![A-Z0-9])[A]{1}[K]{1}[A-Z0-9]{18}(?![A-Z0-9])' * --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')" >> $GITHUB_OUTPUT
+          echo "EOF"  >> $GITHUB_OUTPUT
       - name: Validate if credentials exists  
         if: ${{ steps.command_normal_files.outputs.normal_files_value != '0' }}
         run: |
           echo "::error::AWS credentials was founded, Be careful!"
-          echo "::error::${{ join(steps.command_normal_files.outputs.*, '\n') }}"
+          echo "::error::${{ steps.command_normal_files.outputs.normal_files_value }}"
           exit 1
       - name: Scan for credentials hidden files
         id: command_hidden_files
-        run: echo "hidden_files_value=$(grep -RPHsn '(?<![A-Z0-9])[A]{1}[K]{1}[A-Z0-9]{18}(?![A-Z0-9])' .[^.]* --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')" >> $GITHUB_OUTPUT
+        run: |
+          echo "hidden_files_value<<EOF" >> $GITHUB_OUTPUT
+          echo "$(grep -RPHsn '(?<![A-Z0-9])[A]{1}[K]{1}[A-Z0-9]{18}(?![A-Z0-9])' .[^.]* --exclude=*.tsbuildinfo --exclude-dir=\node_modules --exclude=.gitignore --exclude-dir=\.git --exclude-dir=\dist || echo -n '0')" >> $GITHUB_OUTPUT
+          echo "EOF"  >> $GITHUB_OUTPUT
       - name: Validate if credentials exists in hidden  
         if: ${{ steps.command_hidden_files.outputs.hidden_files_value != '0' }}
         run: |
